# Generated by Django 2.2.14 on 2021-05-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='a', max_length=300),
            preserve_default=False,
        ),
    ]
