"""Initial migration.

Revision ID: d0181483ff63
Revises: 
Create Date: 2021-07-09 01:59:29.760150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0181483ff63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('AuthorID', sa.Integer(), nullable=False),
    sa.Column('AuthorName', sa.String(length=50), nullable=True),
    sa.Column('AuthorBio', sa.String(length=10000), nullable=True),
    sa.PrimaryKeyConstraint('AuthorID')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('authorName', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('genre', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookRatings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=500), nullable=False),
    sa.Column('anonymous', sa.BOOLEAN(), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('nickname', sa.String(length=128), nullable=True),
    sa.Column('physical_address', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book_copies',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saveforlater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('CreditCardNum', sa.String(length=128), nullable=True),
    sa.Column('ExpMonth', sa.Integer(), nullable=True),
    sa.Column('ExpYear', sa.Integer(), nullable=True),
    sa.Column('CVS', sa.Integer(), nullable=True),
    sa.Column('NameOnCard', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ShippingAddr', sa.String(length=128), nullable=True),
    sa.Column('ShippingCity', sa.String(length=128), nullable=True),
    sa.Column('ShippingState', sa.String(length=128), nullable=True),
    sa.Column('ShippingZip', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_shipping')
    op.drop_table('user_card')
    op.drop_table('saveforlater')
    op.drop_table('orders')
    op.drop_table('category')
    op.drop_table('cart')
    op.drop_table('book_copies')
    op.drop_table('user')
    op.drop_table('rating')
    op.drop_table('bookRatings')
    op.drop_table('book')
    op.drop_table('authors')
    # ### end Alembic commands ###
